language: php

dist: xenial

services:
  - mysql
  - postgresql
  - xvfb

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy
      - chromium-chromedriver
      - chromium-browser

env:
  global:
    - COMPOSER_ROOT_VERSION="4.6.x-dev"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    # phpunit tests
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=core PDO=1
    - php: 7.3
      env: DB=MYSQL PHPUNIT_TEST=framework
    - php: 7.4
      env: DB=MYSQL PHPUNIT_TEST=admin
    # behat tests
    - php: 7.1
      env: DB=MYSQL BEHAT_TEST="@admin"
    - php: 7.1
      env: DB=MYSQL BEHAT_TEST="@asset-admin"
    - php: 7.2
      env: DB=MYSQL BEHAT_TEST="@campaign-admin"
    - php: 7.2
      env: DB=MYSQL BEHAT_TEST="@cms"
    - php: 7.3
      env: DB=MYSQL BEHAT_TEST="@elemental-bannerblock"
    - php: 7.3
      env: DB=MYSQL BEHAT_TEST="@siteconfig"
    - php: 7.4
      env: DB=MYSQL BEHAT_TEST="@silverstripe-elemental"
    - php: 7.4
      env: DB=MYSQL BEHAT_TEST="@versioned-admin"

before_script:
# Extra $PATH
  - export PATH=/usr/lib/chromium-browser/:$PATH

# Remove preinstalled Chrome (google-chrome)
  # this would conflict with our chromium-browser installation
  # and its version is incompatible with chromium-chromedriver
  - sudo apt-get remove -y --purge google-chrome-stable || true

# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-testing:^1
  # Fix for running phpunit 5 on php 7.4+
  - composer require --no-update sminnee/phpunit-mock-objects:^3
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:^2; fi
  - if [[ $BEHAT_TEST == "@asset-admin" ]]; then composer require --no-update silverstripe/frameworktest:0.1.0; fi;
  # For testing pull-request branches, this needs to be `composer install` and not `composer update`
  # so that we use a composer.lock file that was created on a local environemnt
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

# Start behat services
  - if [[ $BEHAT_TEST ]]; then mkdir artifacts; fi
  - if [[ $BEHAT_TEST ]]; then cp composer.lock artifacts/; fi
  - if [[ $BEHAT_TEST ]]; then (chromedriver > artifacts/chromedriver.log 2>&1 &); fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php &> artifacts/serve.log &); sleep 3; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit --testsuite $PHPUNIT_TEST; fi
  - if [[ $BEHAT_TEST ]]; then vendor/bin/behat $BEHAT_TEST; fi

after_failure:
  - if [[ $BEHAT_TEST ]]; then php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/; fi
